### ISSUE TITLE
Parsing String

### ISSUE THREAD

**Issue by AhmedSadek60** [AhmedSadek60/AsuMathLabG19#14]
Program should be able to parse string correctly
Parsing string means:

- what type of line is that : definition of matrix or operation of matrices  ? ( defining a variable and calculating its value will be handled in another task by others)

- Execute the code after determining its type 

- Program should detect that there is matrix inside matrix and exclude the inner matrix to be ready to use it later ( you only need to make the inner matrix ready and defined as matrix or put in vector or string. Others will use it and merge it with the big matrix)

**Comment by mohamedelshorbagy** [comment]
I finish the task and Pushed in last commit with other problems like Prefix Expression and Prefix Evaluation
