### ISSUE TITLE
Division in Big Example

### ISSUE THREAD

**Issue by AhmadEbeid** [AhmedSadek60/AsuMathLabG19#2]
when trying the big example a problem happens in the division and no output

![screenshot](https://user-images.githubusercontent.com/11260309/33223749-5e314776-d16b-11e7-8ef7-99c150c385a6.png)

**Comment by amr-galal** [comment]
Also, when working on cmd there's another problem:
![screenshot from 2017-11-24 23-09-18](https://user-images.githubusercontent.com/23275727/33223876-afb5dee4-d16c-11e7-919d-6f660833d8f0.png)

**Comment by mohamedelshorbagy** [comment]
I finish this issue right now in the last commit in the master branch
