### ISSUE TITLE
Trigonometric Functions

### ISSUE THREAD

**Issue by AhmedSadek60** [AhmedSadek60/AsuMathLabG19#8]
Program must at least support sin , cos and tan operations

**Comment by AhmedFathi77** [comment]
issue is solved and i add three functions for sin , cos and tan 
then i added operator sin , cos and tan

**Comment by AhmedFathi77** [comment]
CMatrix.cpp    => operator sin , cos and tan 
CMatrix.h       => Prototypes 
main.c            => sin , cos and tan Functions 
Branch name  => Ahmed Fathi
